// <auto-generated />
using System;
using BldLeague.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BldLeague.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411140500_AddPlayerRankings")]
    partial class AddPlayerRankings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BldLeague.Domain.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LeagueIdentifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("league_identifier");

                    b.HasKey("Id")
                        .HasName("pk_leagues");

                    b.HasIndex("LeagueIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_leagues_league_identifier");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.LeagueSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.HasKey("Id")
                        .HasName("pk_league_seasons");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_league_seasons_season_id");

                    b.HasIndex("LeagueId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_seasons_league_id_season_id");

                    b.ToTable("league_seasons", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.LeagueSeasonStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Best")
                        .HasColumnType("integer")
                        .HasColumnName("best");

                    b.Property<int>("BigPoints")
                        .HasColumnType("integer")
                        .HasColumnName("big_points");

                    b.Property<int>("BonusPoints")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_points");

                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_season_id");

                    b.Property<int>("MatchesLost")
                        .HasColumnType("integer")
                        .HasColumnName("matches_lost");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("matches_played");

                    b.Property<int>("MatchesTied")
                        .HasColumnType("integer")
                        .HasColumnName("matches_tied");

                    b.Property<int>("MatchesWon")
                        .HasColumnType("integer")
                        .HasColumnName("matches_won");

                    b.Property<int>("Place")
                        .HasColumnType("integer")
                        .HasColumnName("place");

                    b.Property<int>("SmallPointsBalance")
                        .HasColumnType("integer")
                        .HasColumnName("small_points_balance");

                    b.Property<int>("SmallPointsGained")
                        .HasColumnType("integer")
                        .HasColumnName("small_points_gained");

                    b.Property<int>("SmallPointsLost")
                        .HasColumnType("integer")
                        .HasColumnName("small_points_lost");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_league_season_standings");

                    b.HasIndex("LeagueSeasonId")
                        .HasDatabaseName("ix_league_season_standings_league_season_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_league_season_standings_user_id");

                    b.ToTable("league_season_standings", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.LeagueSeasonUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_season_id");

                    b.Property<int>("SubleagueGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("subleague_group");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_league_season_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_league_season_users_user_id");

                    b.HasIndex("LeagueSeasonId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_season_users_league_season_id_user_id");

                    b.ToTable("league_season_users", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LeagueSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_season_id");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<int>("UserAAverage")
                        .HasColumnType("integer")
                        .HasColumnName("user_a_average");

                    b.Property<int>("UserABest")
                        .HasColumnType("integer")
                        .HasColumnName("user_a_best");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_a_id");

                    b.Property<int>("UserAScore")
                        .HasColumnType("integer")
                        .HasColumnName("user_a_score");

                    b.Property<int>("UserBAverage")
                        .HasColumnType("integer")
                        .HasColumnName("user_b_average");

                    b.Property<int>("UserBBest")
                        .HasColumnType("integer")
                        .HasColumnName("user_b_best");

                    b.Property<Guid?>("UserBId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_b_id");

                    b.Property<int>("UserBScore")
                        .HasColumnType("integer")
                        .HasColumnName("user_b_score");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("LeagueSeasonId")
                        .HasDatabaseName("ix_matches_league_season_id");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_matches_round_id");

                    b.HasIndex("UserAId")
                        .HasDatabaseName("ix_matches_user_a_id");

                    b.HasIndex("UserBId")
                        .HasDatabaseName("ix_matches_user_b_id");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.PlayerRanking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AverageRank")
                        .HasColumnType("integer")
                        .HasColumnName("average_rank");

                    b.Property<Guid?>("AverageRoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("average_round_id");

                    b.Property<int?>("AverageSolve1")
                        .HasColumnType("integer")
                        .HasColumnName("average_solve1");

                    b.Property<int?>("AverageSolve2")
                        .HasColumnType("integer")
                        .HasColumnName("average_solve2");

                    b.Property<int?>("AverageSolve3")
                        .HasColumnType("integer")
                        .HasColumnName("average_solve3");

                    b.Property<int?>("AverageSolve4")
                        .HasColumnType("integer")
                        .HasColumnName("average_solve4");

                    b.Property<int?>("AverageSolve5")
                        .HasColumnType("integer")
                        .HasColumnName("average_solve5");

                    b.Property<int?>("BestAverage")
                        .HasColumnType("integer")
                        .HasColumnName("best_average");

                    b.Property<int?>("BestSingle")
                        .HasColumnType("integer")
                        .HasColumnName("best_single");

                    b.Property<int?>("SingleRank")
                        .HasColumnType("integer")
                        .HasColumnName("single_rank");

                    b.Property<Guid?>("SingleRoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("single_round_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_player_rankings");

                    b.HasIndex("AverageRoundId")
                        .HasDatabaseName("ix_player_rankings_average_round_id");

                    b.HasIndex("SingleRoundId")
                        .HasDatabaseName("ix_player_rankings_single_round_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_rankings_user_id");

                    b.ToTable("PlayerRankings", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("SubmissionFormUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("submission_form_url");

                    b.HasKey("Id")
                        .HasName("pk_rounds");

                    b.HasIndex("SeasonId", "RoundNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_rounds_season_id_round_number");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.RoundStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Average")
                        .HasColumnType("integer")
                        .HasColumnName("average");

                    b.Property<int>("Best")
                        .HasColumnType("integer")
                        .HasColumnName("best");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<int>("Place")
                        .HasColumnType("integer")
                        .HasColumnName("place");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<int>("Solve1")
                        .HasColumnType("integer")
                        .HasColumnName("solve1");

                    b.Property<int>("Solve2")
                        .HasColumnType("integer")
                        .HasColumnName("solve2");

                    b.Property<int>("Solve3")
                        .HasColumnType("integer")
                        .HasColumnName("solve3");

                    b.Property<int>("Solve4")
                        .HasColumnType("integer")
                        .HasColumnName("solve4");

                    b.Property<int>("Solve5")
                        .HasColumnType("integer")
                        .HasColumnName("solve5");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_round_standings");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_round_standings_league_id");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_round_standings_round_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_round_standings_user_id");

                    b.ToTable("round_standings", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Scramble", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Notation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notation");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<int>("ScrambleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("scramble_number");

                    b.HasKey("Id")
                        .HasName("pk_scrambles");

                    b.HasIndex("RoundId", "ScrambleNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_scrambles_round_id_scramble_number");

                    b.ToTable("scrambles", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("SeasonNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_season_number");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Solve", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_solves");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_solves_match_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_solves_user_id");

                    b.ToTable("solves", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_thumbnail_url");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("WcaId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("wca_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("WcaId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_wca_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.LeagueSeason", b =>
                {
                    b.HasOne("BldLeague.Domain.Entities.League", "League")
                        .WithMany("LeagueSeasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_seasons_leagues_league_id");

                    b.HasOne("BldLeague.Domain.Entities.Season", "Season")
                        .WithMany("LeagueSeasons")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_seasons_season_season_id");

                    b.Navigation("League");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.LeagueSeasonStanding", b =>
                {
                    b.HasOne("BldLeague.Domain.Entities.LeagueSeason", "LeagueSeason")
                        .WithMany("LeagueSeasonStandings")
                        .HasForeignKey("LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_standings_league_seasons_league_season_id");

                    b.HasOne("BldLeague.Domain.Entities.User", "User")
                        .WithMany("LeagueSeasonStandings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_standings_user_user_id");

                    b.Navigation("LeagueSeason");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.LeagueSeasonUser", b =>
                {
                    b.HasOne("BldLeague.Domain.Entities.LeagueSeason", "LeagueSeason")
                        .WithMany("LeagueSeasonUsers")
                        .HasForeignKey("LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_users_league_seasons_league_season_id");

                    b.HasOne("BldLeague.Domain.Entities.User", "User")
                        .WithMany("LeagueSeasonUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_users_user_user_id");

                    b.Navigation("LeagueSeason");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Match", b =>
                {
                    b.HasOne("BldLeague.Domain.Entities.LeagueSeason", "LeagueSeason")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_league_seasons_league_season_id");

                    b.HasOne("BldLeague.Domain.Entities.Round", "Round")
                        .WithMany("Matches")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_round_round_id");

                    b.HasOne("BldLeague.Domain.Entities.User", "UserA")
                        .WithMany("MatchesAsUserA")
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_user_user_a_id");

                    b.HasOne("BldLeague.Domain.Entities.User", "UserB")
                        .WithMany("MatchesAsUserB")
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_matches_user_user_b_id");

                    b.Navigation("LeagueSeason");

                    b.Navigation("Round");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.PlayerRanking", b =>
                {
                    b.HasOne("BldLeague.Domain.Entities.Round", "AverageRound")
                        .WithMany()
                        .HasForeignKey("AverageRoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_player_rankings_round_average_round_id");

                    b.HasOne("BldLeague.Domain.Entities.Round", "SingleRound")
                        .WithMany()
                        .HasForeignKey("SingleRoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_player_rankings_round_single_round_id");

                    b.HasOne("BldLeague.Domain.Entities.User", "User")
                        .WithOne("PlayerRanking")
                        .HasForeignKey("BldLeague.Domain.Entities.PlayerRanking", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_rankings_user_user_id");

                    b.Navigation("AverageRound");

                    b.Navigation("SingleRound");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Round", b =>
                {
                    b.HasOne("BldLeague.Domain.Entities.Season", "Season")
                        .WithMany("Rounds")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rounds_season_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.RoundStanding", b =>
                {
                    b.HasOne("BldLeague.Domain.Entities.League", "League")
                        .WithMany("RoundStandings")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_round_standings_leagues_league_id");

                    b.HasOne("BldLeague.Domain.Entities.Round", "Round")
                        .WithMany("Standings")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_round_standings_rounds_round_id");

                    b.HasOne("BldLeague.Domain.Entities.User", "User")
                        .WithMany("RoundStandings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_round_standings_user_user_id");

                    b.Navigation("League");

                    b.Navigation("Round");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Scramble", b =>
                {
                    b.HasOne("BldLeague.Domain.Entities.Round", "Round")
                        .WithMany("Scrambles")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scrambles_rounds_round_id");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Solve", b =>
                {
                    b.HasOne("BldLeague.Domain.Entities.Match", "Match")
                        .WithMany("Solves")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solves_matches_match_id");

                    b.HasOne("BldLeague.Domain.Entities.User", "User")
                        .WithMany("Solves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solves_user_user_id");

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.League", b =>
                {
                    b.Navigation("LeagueSeasons");

                    b.Navigation("RoundStandings");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.LeagueSeason", b =>
                {
                    b.Navigation("LeagueSeasonStandings");

                    b.Navigation("LeagueSeasonUsers");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Match", b =>
                {
                    b.Navigation("Solves");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Round", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Scrambles");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.Season", b =>
                {
                    b.Navigation("LeagueSeasons");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("BldLeague.Domain.Entities.User", b =>
                {
                    b.Navigation("LeagueSeasonStandings");

                    b.Navigation("LeagueSeasonUsers");

                    b.Navigation("MatchesAsUserA");

                    b.Navigation("MatchesAsUserB");

                    b.Navigation("PlayerRanking");

                    b.Navigation("RoundStandings");

                    b.Navigation("Solves");
                });
#pragma warning restore 612, 618
        }
    }
}
